#!/usr/bin/env sh

# DEBUGGING

# directory containing log files HOMEBREW_PREFIX/var/log/yabai/
# HOMEBREW_PREFIX defaults to /opt/homebrew

# # view the last lines of the error log 
# tail -f /opt/homebrew/var/log/yabai/yabai.err.log

# # view the last lines of the debug log
# tail -f /opt/homebrew/var/log/yabai/yabai.out.log

# 📖 DOCUMENTATION
# https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc

# # Terminology
# managed - a tile window (which is different from float)


# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config external_bar all:36:0

# GLOBAL SETTINGS
yabai -m config debug_output on
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
# OPACITY
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        0.98
yabai -m config normal_window_opacity        0.8
# BORDERS
yabai -m config window_border                off
yabai -m config window_border_hidpi          on # for retina displays; uses a lot more memory
yabai -m config window_border_width          2
yabai -m config window_border_radius         2
yabai -m config active_window_border_color   0xFF40D61A
yabai -m config normal_window_border_color   0xFFFFFFFF
yabai -m config insert_feedback_color        0xFFFFFFFF
# SPLIT
yabai -m config split_ratio                  0.50
yabai -m config split_type                   auto
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# GENERAL SPACE SETTINGS
yabai -m config layout                       bsp # bsp stands for binary space partitioning
yabai -m config top_padding                  02
yabai -m config bottom_padding               02
yabai -m config left_padding                 02
yabai -m config right_padding                02
yabai -m config window_gap                   04

# SPECIFIC SPACE LAYOUTS
yabai -m space 1 --layout stack --label web
yabai -m space 2 --label docs
yabai -m space 3 --layout stack --label office
yabai -m space 4 --label develop

# RULES

# Charlie OS Utils
yabai -m rule --add app="^Clockify Desktop$" sticky=on # manage=off
yabai -m rule --add app="KeePassXC" sticky=on manage=off

yabai -m rule --add app="^System Settings$" manage=off #  display=east
yabai -m rule --add app="Terminal" manage=off # needs to be in float because of a weird behavior with multiple tabs


# Web browsers SPACE 1
# yabai -m rule --add app="^Brave$" border=off  layer=below
yabai -m rule --add app="Floorp" space=^1
yabai -m rule --add app="Arc" space=^1
# yabai -m rule --add app="^(Google Chrome|Firefox)$" border=off space=^web 

# DOCUMENTATION SPACE 2
yabai -m rule --add app="Logseq" space=^2

# OFFICE SPACE 3 (Stack)
yabai -m rule --add app="Teams" space=3 # manage=off
yabai -m rule --add app="Slack" space=3 # manage=off
yabai -m rule --add app="Mail" space=^3 # manage=off

# Development - Text editors SPACE 4
# Only one app per space needs borders
yabai -m rule --add app="Code" space=^4

# https://github.com/koekeishiya/yabai/issues/1622

# yabai -m rule --add app="^Arc$" subrole='AXSystemDialog' manage=off mouse_follows_focus=off
yabai -m rule --add subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off

echo "yabai configuration loaded.."
