#!/usr/bin/env sh

# DEBUGGING

# directory containing log files HOMEBREW_PREFIX/var/log/yabai/
# HOMEBREW_PREFIX defaults to /opt/homebrew

# # view the last lines of the error log 
# tail -f /opt/homebrew/var/log/yabai/yabai.err.log

# # view the last lines of the debug log
# tail -f /opt/homebrew/var/log/yabai/yabai.out.log

# 📖 DOCUMENTATION
# https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc

# # Terminology
# managed - a tile window (which is different from float)


# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config external_bar all:36:0

# GLOBAL SETTINGS
yabai -m config debug_output on
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
# OPACITY
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        0.98
yabai -m config normal_window_opacity        0.8
# BORDERS
yabai -m config window_border                off
yabai -m config window_border_hidpi          on # for retina displays; uses a lot more memory
yabai -m config window_border_width          2
yabai -m config window_border_radius         2
yabai -m config active_window_border_color   0xFF40D61A
yabai -m config normal_window_border_color   0xFFFFFFFF
yabai -m config insert_feedback_color        0xFFFFFFFF
# SPLIT
yabai -m config split_ratio                  0.50
yabai -m config split_type                   auto
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# GENERAL SPACE SETTINGS
yabai -m config layout                       bsp # bsp stands for binary space partitioning
yabai -m config top_padding                  04
yabai -m config bottom_padding               04
yabai -m config left_padding                 04
yabai -m config right_padding                04
yabai -m config window_gap                   10

# SPECIFIC SPACE LAYOUTS
yabai -m space 1 --layout stack --label ops
yabai -m space 2 --layout stack --label impl
yabai -m space 3 --label other

# RULES

# Charlie OS Utils
yabai -m rule --add app="^Clockify Desktop$" sticky=on manage=off
yabai -m rule --add app="^KeePassXC$" sticky=on manage=off
yabai -m rule --add app="^System Settings$" sticky=on manage=off
yabai -m rule --add app="^Notes$" sticky=on manage=off
# yabai -m rule --add app="^Terminal$" sticky=on manage=off # needs to be in float because of a weird behavior with multiple tabs
yabai -m rule --add app="^Jan$" sticky=on manage=off


# SPACE 1 (operations, administration)
# yabai -m rule --add app="^Brave$" border=off  layer=below
yabai -m rule --add app="Arc" space=^1
# yabai -m rule --add app="^(Google Chrome|Firefox)$" border=off space=^web 

#  SPACE 2 (implementation)
# yabai -m rule --add app="Logseq" space=^2
# yabai -m rule --add app="Obsidian" space=^2

# https://github.com/koekeishiya/yabai/issues/1622

yabai -m rule --add app="Ghostty" subrole="^AXFloatingWindow$" sticky=on manage=off mouse_follows_focus=off


# yabai -m rule --add app="^Arc$" subrole='AXSystemDialog' manage=off mouse_follows_focus=off
yabai -m rule --add subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off

# The following rules fix the weird bug for rendering windows of apllications which support the native macOS tabs
# The fix 👇 makes the situation worse because it breaks the stack layout (and I need that fix only for tabs which I don't use)
# yabai -m signal --add app='^Ghostty$' event=window_created action='yabai -m space --layout bsp'
# yabai -m signal --add app='^Ghostty$' event=window_destroyed action='yabai -m space --layout bsp'

yabai -m signal --add app='^Finder$' event=window_created action='yabai -m space --layout bsp'
yabai -m signal --add app='^Finder$' event=window_destroyed action='yabai -m space --layout bsp'

yabai -m signal --add app='^Terminal$' event=window_created action='yabai -m space --layout bsp'
yabai -m signal --add app='^Terminal$' event=window_destroyed action='yabai -m space --layout bsp'

# jankyborders
# borders active_color=0xff7eae77 inactive_color=0xff494d64 width=8.0 & # the inactive color is invisible, maybe black?
borders active_color=0xff5a9654 inactive_color=0xffb76666 width=10.0
# borders active_color=0xff7eae77 inactive_color=0xffe6a8a8 width=6.0 & # the inactive color is pastel red

echo "yabai configuration loaded.."
